name: FishsCustomMobs
main: com.thefishnextdoor.custommobs.FishsCustomMobs
version: 0.0.1
api-version: 1.20
author: TheFishNextDoor
description: Custom Mobs Plugin
commands:
  fcm:
    description: Main command for FishsCustomMobs
    usage: /fcm <subcommand>
    aliases:
    - fishscustommobs
    - custommobs
permissions:
  fcm.reload:
    description: Permission to reload the plugin
  fcm.summon:
    description: Permission to summon custom mobs
  fcm.give:
    description: Permission to give custom items